version: "3"

services:
  wristwatch-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wristwatch-app
    restart: unless-stopped
    command: >
      sh -c "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    networks:
      - personal_network

  mysql-db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ndquang@2002
      MYSQL_DATABASE: wristwatches_db
      MYSQL_USER: ndquang
      MYSQL_PASSWORD: ndquang@2002
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - personal_network

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8888:80"
    depends_on:
      - mysql-db
    networks:
      - personal_network

volumes:
  dbdata:

networks:
  personal_network:
    driver: bridge